# 日志路径,相对路径
logging:
  file:
    path: ../logs

spring:
  datasource:
    db1: #配置数据源1:此处配置的mysql数据库
      driverClassName: com.mysql.cj.jdbc.Driver
      username: wiscom
      password: wiscom@123
      # spring2.0此处为jdbc-url
      jdbc-url: jdbc:mysql://10.185.212.244:3306/hence?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      #db2: #配置数据源2,此处配置的是postgre数据库
      #jdbc-url: jdbc:postgresql://10.0.19.71:5432/analyzedb
      #username: njgjjt
      #password: 123456
      #driverClassName: org.postgresql.Driver
      #    platform: postgres
      #type: com.alibaba.druid.pool.DruidDataSource
      initialization-mode: always
    # ============================== druid ============================== #
    druid:
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j
      # ============================== redis ============================== #
  redis:
    database: 1
    host: 172.20.134.60
    port: 6379  # Redis服务器连接端口
    timeout: 5000 # 连接超时时间（毫秒）
    password: redis123     # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0



server:
  port: 9041

  ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://10.185.212.244:7010/xxl-job-admin
        ### xxl-job, access token
    accessToken:
    executor:
      appname: hence
      ip:
      port: 9998
      ### xxl-job log path
      logpath: ./logs/jobhandler
      ### xxl-job log retention days
      logretentiondays: 30